# Generated by Django 3.0.5 on 2020-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.IntegerField(blank=True, choices=[('0', '男'), ('0', '女')], null=True)),
            ],
        ),
    ]
