# Generated by Django 3.0.5 on 2020-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200423_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
    ]
